import ClassroomUser from '@/applications/double6/ClassroomUser'
import CommonClass from '@/applications/double6/CommonClass'
import CourseRecord from '@/applications/double6/CourseRecord'
import Region from '@/applications/double6/Region'
import Resources from '@/applications/double6/Resources'
import School from '@/applications/double6/School'
import SectionRecord from '@/applications/double6/SectionRecord'
import StatisticUser from '@/applications/double6/StatisticUser'
import StatisticUserDay from '@/applications/double6/StatisticUserDay'
import StatisticUserRecord from '@/applications/double6/StatisticUserRecord'
import StudyPlan from '@/applications/double6/StudyPlan'
import StudyRecord from '@/applications/double6/StudyRecord'
import Teacher from '@/applications/double6/Teacher'
import TeacherClass from '@/applications/double6/TeacherClass'
import UserCourse from '@/applications/double6/UserCourse'
import WordCalligraphy from '@/applications/double6/WordCalligraphy'
import WordPoint from '@/applications/double6/WordPoint'
import WordSplit from '@/applications/double6/WordSplit'
import WordSystem from '@/applications/double6/WordSystem'

export default {ClassroomUser, CommonClass, CourseRecord, Region, Resources, School, SectionRecord, StatisticUser, StatisticUserDay, StatisticUserRecord, StudyPlan, StudyRecord, Teacher, TeacherClass, UserCourse, WordCalligraphy, WordPoint, WordSplit, WordSystem}
